### ISSUE TITLE
Story map creation

### ISSUE THREAD

**Issue by npch** [softwaresaved/hybrid-event-guide#4]
- [x] Build from Personas we've [brainstormed](https://docs.google.com/presentation/d/1mIvptG5VV_POmkqsbYgj-y3lY9EY0U4fzw9S1_le7jw/edit?pli=1#slide=id.g7f7da1891a_3_0): 
- [x] Identify why people want to join?
- [x] What’s stopping people from joining / painpoints
- [x] Swimlanes for participants and organisers

**Comment by emmyft** [comment]
We redacted the original personas to protect personal information. 

We've also created the initial map and documented the process, as well as how to contribute at [storymaps.md](https://github.com/softwaresaved/hybrid-event-guide/blob/master/storymaps.md)
